import Head from "next/head"
import Header from "@/components/header"
import HorizontalCards from "@/components/horizontalCards"
import ShuffleCards from "@/components/shuffleCards"
import Video from "@/components/video"
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header>
          <h1>Film maker</h1>
        </Header>
        <ShuffleCards />
        <div className={styles.context}>
          We love to visualize stories
          <br /> because we love people and they inspire us.
        </div>
        <Video />
        <div className={styles.context}>
          We are a creative agency, film production,
          <br /> branded & original content creators.
        </div>
        <div className={styles.container}>
          <HorizontalCards />
        </div>
      </main>
    </>
  )
}
