import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from '@/components/header'
import HorizontalCards from '@/components/horizontalCards'
import ShuffleCards from "@/components/shuffleCards"
import Video from "@/components/video"


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header>
          <h1>Film maker</h1>
        </Header>
        <HorizontalCards />
        <ShuffleCards />
        <Video />
      </main>
    </>
  )
}
